### ISSUE TITLE
scanline artifacts or a striped graphical glitch

### ISSUE THREAD

**Issue by Mart-01-oss** [leegao/bionic-vulkan-wrapper#126]
![Image](https://github.com/user-attachments/assets/289be0d5-53be-4c5e-b9ae-a44542824456)

[Dead Space_d3d9.log](https://github.com/user-attachments/files/21749106/Dead.Space_d3d9.log)

[wrapper_log_2025_08_13_15_18_24.Dead Space.exe.28296.txt](https://github.com/user-attachments/files/21749110/wrapper_log_2025_08_13_15_18_24.Dead.Space.exe.28296.txt)

The cmd logs is huge maybe it can be optimize by printing singleline (VK_.. = 10) instead of 10times of similar line's.

**Comment by leegao** [comment]
if you zip the cmd logs, it'll usually be much smaller

**Comment by Mart-01-oss** [comment]
> if you zip the cmd logs, it'll usually be much smaller

done already uploaded it
do you think the bug is clip distance?

**Comment by leegao** [comment]
> https://drive.usercontent.google.com/download?id=1Fu0krvpyNdMEnh9BTWF7tTQuXbuNidYM&export=download&authuser=0

looks like I get a

```
We're sorry, but you do not have access to this page. That’s all we know.
```

**Comment by Mart-01-oss** [comment]
> > https://drive.usercontent.google.com/download?id=1Fu0krvpyNdMEnh9BTWF7tTQuXbuNidYM&export=download&authuser=0
> 
> looks like I get a
> 
> ```
> We're sorry, but you do not have access to this page. That’s all we know.
> ```

ohh sorry my fault here's the link 
https://drive.usercontent.google.com/download?id=1Fu0krvpyNdMEnh9BTWF7tTQuXbuNidYM&export=download&authuser=0&confirm=t&uuid=47fa9fb6-3ec3-49b7-8e86-508be506d26f&at=AN8xHorX1VIAXLFATGbZdk63LXnP%3A1755071770779&pli=1

**Comment by leegao** [comment]
> > > https://drive.usercontent.google.com/download?id=1Fu0krvpyNdMEnh9BTWF7tTQuXbuNidYM&export=download&authuser=0
> > 
> > 
> > looks like I get a
> > ```
> > We're sorry, but you do not have access to this page. That’s all we know.
> > ```
> 
> ohh sorry my fault here's the link https://drive.usercontent.google.com/download?id=1Fu0krvpyNdMEnh9BTWF7tTQuXbuNidYM&export=download&authuser=0&confirm=t&uuid=47fa9fb6-3ec3-49b7-8e86-508be506d26f&at=AN8xHorX1VIAXLFATGbZdk63LXnP%3A1755071770779&pli=1

@Mart-01-oss still no access, if it's not too big, you can zip it and upload it here?

**Comment by Mart-01-oss** [comment]
[wrapper_cmds_2025_08_13_16_06_49.Dead Space.exe.15523.zip](https://github.com/user-attachments/files/21749670/wrapper_cmds_2025_08_13_16_06_49.Dead.Space.exe.15523.zip)

**Comment by leegao** [comment]
@Mart-01-oss - potentially a long shot, but can you try the new vulkan validation layer (USE_VVL) integration in https://github.com/leegao/bionic-vulkan-wrapper/releases/tag/v0.0.5r1? You'll also need to download and extract the [libVkLayer_khronos_validation.so.zip](https://github.com/leegao/bionic-vulkan-wrapper/releases/download/v0.0.5r1/libVkLayer_khronos_validation.so.zip) into the same place libvulkan_wrapper.so

This will help me identify what features are actually being used by the game that's not supported (otherwise, it may just be a strange quirk of Mali for some specific vulkan api)

**Comment by Mart-01-oss** [comment]
can't open the game probably missing lib
cant find any related to this lib libgraphicsenv.so

[000.00] Found "_ZN7android11GraphicsEnv11getInstanceEv" in libgraphicsenv.so at 0x74973efb60 	 (set_layer_paths:32)
[000.00] Found "_ZN7android11GraphicsEnv13getLayerPathsEv" in libgraphicsenv.so at 0x74973f1990 	 (set_layer_paths:33)
[000.00] Found "_ZN7android11GraphicsEnv15getAppNamespaceEv" in libgraphicsenv.so at 0x74973f1980 	 (set_layer_paths:34)
[000.00] [ERROR] Cannot find symbol in libgraphicsenv.so: "_ZN7android11GraphicsEnv13setLayerPathsEPNS_21NativeLoaderNamespaceENSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE" 	 (set_layer_paths:35)
[000.00] get_vulkan_handle: defaulting to /system/lib64/libvulkan.so 	 (get_vulkan_handle_icd:81)
[000.03] [ERROR] Failed to intercept GraphicsEnv::SetLayerPaths(), cannot load VVL 	 (__wrapper_CreateInstance:374)

**Comment by leegao** [comment]
Oh interesting, if you can, can you grab `/system/lib64/libgraphicsenv.so` on your device?

**Comment by Mart-01-oss** [comment]
> Oh interesting, if you can, can you grab `/system/lib64/libgraphicsenv.so` on your device?

[libgraphicsenv.zip](https://github.com/user-attachments/files/21751949/libgraphicsenv.zip)

**Comment by leegao** [comment]
New pattern is `_ZN7android11GraphicsEnv13setLayerPathsEPNS_21NativeLoaderNamespaceERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE`

which corresponds to

```
android::GraphicsEnv::setLayerPaths(android::NativeLoaderNamespace*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
```

vs the older

```
android::GraphicsEnv::setLayerPaths(android::NativeLoaderNamespace*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
```

basically this has changed from a pass by copy to reference.

[libvulkan_wrapper.so.zip](https://github.com/user-attachments/files/21752432/libvulkan_wrapper.so.zip)

see if this works for you now

**Comment by Mart-01-oss** [comment]
Great.it works now(vvl) then game crash
(updated logs)

[vvl_2025_08_13_18_53_50.Dead Space.exe.13616.txt](https://github.com/user-attachments/files/21752837/vvl_2025_08_13_18_53_50.Dead.Space.exe.13616.txt)

[wrapper_cmds_2025_08_13_18_53_50.Dead Space.exe.13616.txt](https://github.com/user-attachments/files/21752839/wrapper_cmds_2025_08_13_18_53_50.Dead.Space.exe.13616.txt)

[wrapper_log_2025_08_13_18_53_50.Dead Space.exe.13616.txt](https://github.com/user-attachments/files/21752841/wrapper_log_2025_08_13_18_53_50.Dead.Space.exe.13616.txt)

**Comment by leegao** [comment]
Crash may be the validation catching something that shouldn't be happening (so good news), I'll take a look tomorrow!

**Comment by leegao** [comment]
I'll take a closer look at the vvl logs, in the mean time, the new update that can dump all of the artifacts is out at https://github.com/leegao/bionic-vulkan-wrapper/releases/tag/v0.0.5r2 (`DUMP_BCN_ARTIFACTS=1`, `WRAPPER_CMD_LOG_LEVEL=trace,debug1,gfx`, and probably `USE_VVL=0` to avoid the validation crash), if you upload the artifacts_...zip as well, I can go through them and compare against a reference implementation to see if there are any obvious problems

**Comment by leegao** [comment]
May be related to #129 after enabling vvl due to

```
Validation Error: [ VUID-VkBindBufferMemoryInfo-memory-02985 ] | MessageID = 0xf0a015da
vkBindBufferMemory2(): pBindInfos[0].memory (VkDeviceMemory 0x410000000041) was created with an import operation with handleType of VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT which is not set in the VkBuffer (VkBuffer 0x420000000042) VkExternalMemoryBufferCreateInfo::handleType (VkExternalMemoryHandleTypeFlags(0)).
The Vulkan spec states: If memory was allocated by a memory import operation, that is not VkImportAndroidHardwareBufferInfoANDROID with a non-NULL buffer value, the external handle type of the imported memory must also have been set in VkExternalMemoryBufferCreateInfo::handleTypes when buffer was created (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkBindBufferMemoryInfo-memory-02985)
Objects: 2
    [0] VkBuffer 0x420000000042
    [1] VkDeviceMemory 0x410000000041
```

**Comment by leegao** [comment]
```
Validation Information: [ WARNING-CreateInstance-status-message ] | MessageID = 0x23dfd876
vkCreateInstance(): Khronos Validation Layer Active:
    Current Enables: VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT.
    Current Disables: None.

Objects: 1
    [0] VkInstance 0xb4000075198f5f10
Validation Information: [ WARNING-cache-file-error ] | MessageID = 0xb8515d13
vkCreateDevice(): Cannot open shader validation cache at /tmp/shader_validation_cache-10760.bin for reading (it may not exist yet)

Validation Error: [ VUID-VkBindBufferMemoryInfo-memory-02985 ] | MessageID = 0xf0a015da
vkBindBufferMemory2(): pBindInfos[0].memory (VkDeviceMemory 0x70000000007) was created with an import operation with handleType of VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT which is not set in the VkBuffer (VkBuffer 0x50000000005) VkExternalMemoryBufferCreateInfo::handleType (VkExternalMemoryHandleTypeFlags(0)).
The Vulkan spec states: If memory was allocated by a memory import operation, that is not VkImportAndroidHardwareBufferInfoANDROID with a non-NULL buffer value, the external handle type of the imported memory must also have been set in VkExternalMemoryBufferCreateInfo::handleTypes when buffer was created (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkBindBufferMemoryInfo-memory-02985)
Objects: 2
    [0] VkBuffer 0x50000000005
    [1] VkDeviceMemory 0x70000000007

...

Validation Error: [ VUID-vkBindImageMemory-memory-02989 ] | MessageID = 0xcf1631af
vkBindImageMemory(): memory (VkDeviceMemory 0x180000000018) was created with an import operation with handleType of VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT which is not set in the VkImage (VkImage 0x1a000000001a) VkExternalMemoryImageCreateInfo::handleType (VkExternalMemoryHandleTypeFlags(0)).
The Vulkan spec states: If memory was created by a memory import operation, that is not VkImportAndroidHardwareBufferInfoANDROID with a non-NULL buffer value, the external handle type of the imported memory must also have been set in VkExternalMemoryImageCreateInfo::handleTypes when image was created (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-vkBindImageMemory-memory-02989)
Objects: 2
    [0] VkImage 0x1a000000001a
    [1] VkDeviceMemory 0x180000000018

Validation Error: [ VUID-VkImportMemoryWin32HandleInfoKHR-handleType-09861 ] | MessageID = 0xbd3c59bc
vkBindImageMemory(): memory (VkDeviceMemory 0x180000000018) was imported from handleType VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT but VkExternalImageFormatProperties does not report it as importable.
The Vulkan spec states: If handleType is not 0, it must be supported for import, as reported by VkExternalTensorPropertiesARM, VkExternalImageFormatProperties, or VkExternalBufferProperties (https://docs.vulkan.org/spec/latest/chapters/memory.html#VUID-VkImportMemoryWin32HandleInfoKHR-handleType-09861)
Objects: 2
    [0] VkImage 0x1a000000001a
    [1] VkDeviceMemory 0x180000000018

...

Validation Error: [ VUID-VkBindBufferMemoryInfo-memory-02985 ] | MessageID = 0xf0a015da
vkBindBufferMemory2(): pBindInfos[0].memory (VkDeviceMemory 0x410000000041) was created with an import operation with handleType of VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT which is not set in the VkBuffer (VkBuffer 0x3f000000003f) VkExternalMemoryBufferCreateInfo::handleType (VkExternalMemoryHandleTypeFlags(0)).
The Vulkan spec states: If memory was allocated by a memory import operation, that is not VkImportAndroidHardwareBufferInfoANDROID with a non-NULL buffer value, the external handle type of the imported memory must also have been set in VkExternalMemoryBufferCreateInfo::handleTypes when buffer was created (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkBindBufferMemoryInfo-memory-02985)
Objects: 2
    [0] VkBuffer 0x3f000000003f
    [1] VkDeviceMemory 0x410000000041

...

Validation Error: [ VUID-VkImageCreateInfo-pNext-pNext ] | MessageID = 0x69dad144
vkCreateImage(): pCreateInfo->pNext chain includes a structure with unknown VkStructureType (1000001002).
pNext -> [Unknown VkStructureType 1000001002]
This error is based on the Valid Usage documentation for version 321 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case the use of pCreateInfo->pNext is undefined and may not work correctly with validation enabled.
The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of VkBufferCollectionImageCreateInfoFUCHSIA, VkDedicatedAllocationImageCreateInfoNV, VkExportMetalObjectCreateInfoEXT, VkExternalFormatANDROID, VkExternalFormatQNX, VkExternalMemoryImageCreateInfo, VkExternalMemoryImageCreateInfoNV, VkImageAlignmentControlCreateInfoMESA, VkImageCompressionControlEXT, VkImageDrmFormatModifierExplicitCreateInfoEXT, VkImageDrmFormatModifierListCreateInfoEXT, VkImageFormatListCreateInfo, VkImageStencilUsageCreateInfo, VkImageSwapchainCreateInfoKHR, VkImportMetalIOSurfaceInfoEXT, VkImportMetalTextureInfoEXT, VkOpaqueCaptureDescriptorDataCreateInfoEXT, VkOpticalFlowImageFormatInfoNV, or VkVideoProfileListInfoKHR (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkImageCreateInfo-pNext-pNext)

Validation Error: [ VUID-VkImageCreateInfo-pNext-01974 ] | MessageID = 0xee97da05
vkCreateImage(): pCreateInfo->pNext<VkExternalFormatANDROID>.externalFormat (40) is non-zero, format is VK_FORMAT_R8G8B8A8_UNORM.
The Vulkan spec states: If the pNext chain includes a VkExternalFormatANDROID structure, and its externalFormat member is non-zero the format must be VK_FORMAT_UNDEFINED (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkImageCreateInfo-pNext-01974)

Validation Error: [ VUID-VkImageCreateInfo-pNext-02397 ] | MessageID = 0xcac730da
vkCreateImage(): pCreateInfo->pNext<VkExternalFormatANDROID>.externalFormat (40) is non-zero, but usage is VK_IMAGE_USAGE_TRANSFER_DST_BIT.
The Vulkan spec states: If the pNext chain includes a VkExternalFormatANDROID structure whose externalFormat member is not 0, usage must not include any usages except VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, or VK_IMAGE_USAGE_SAMPLED_BIT (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkImageCreateInfo-pNext-02397)

Validation Error: [ VUID-VkImageCreateInfo-pNext-02398 ] | MessageID = 0xc94b7919
vkCreateImage(): pCreateInfo->pNext<VkExternalFormatANDROID>.externalFormat (40) is non-zero, but layout is VK_IMAGE_TILING_LINEAR.
The Vulkan spec states: If the pNext chain includes a VkExternalFormatANDROID structure whose externalFormat member is not 0, tiling must be VK_IMAGE_TILING_OPTIMAL (https://docs.vulkan.org/spec/latest/chapters/resources.html#VUID-VkImageCreateInfo-pNext-02398)
```

**Comment by leegao** [comment]
Crashing at

```
dispatch->GetAndroidHardwareBufferPropertiesANDROID (id=3728)
wrapper_CreateImage (id=3729)
  in: device: VkDevice (handle) = 0xb4000074f98eeb30 (id=3729)
  in: pCreateInfo: VkImageCreateInfo* (id=3729)
    .flags: VkImageCreateFlags = 0x0
    .imageType: VkImageType = 0x1
    .format: VkFormat = 0x25
    .extent: VkExtent3D
      .width: uint32_t = 0x500
      .height: uint32_t = 0x2d0
      .depth: uint32_t = 0x1
    .mipLevels: uint32_t = 0x1
    .arrayLayers: uint32_t = 0x1
    .samples: VkSampleCountFlagBits = 0x1
    .tiling: VkImageTiling = 0x1
    .usage: VkImageUsageFlags = 0x2
    .sharingMode: VkSharingMode = 0x0
    .queueFamilyIndexCount: uint32_t = 0x1
    .pQueueFamilyIndices[0]: uint32_t* = 0x0
    .initialLayout: VkImageLayout = 0x0
    .pNext(VkExternalMemoryImageCreateInfo)
      .handleTypes: VkExternalMemoryHandleTypeFlags = 0x400
    .pNext(VkExternalFormatANDROID)
      .externalFormat: uint64_t = 0x28
  in: pAllocator: VkAllocationCallbacks* (id=3729)
    .pUserData: void* = 0x0
    .pfnAllocation: PFN_vkAllocationFunction = 0x73e3871114
    .pfnReallocation: PFN_vkReallocationFunction = 0x73e387111c
    .pfnFree: PFN_vkFreeFunction = 0x73e3871128
    .pfnInternalAllocation: PFN_vkInternalAllocationNotification = 0x0
    .pfnInternalFree: PFN_vkInternalFreeNotification = 0x0
```

**Comment by leegao** [comment]
@Mart-01-oss - https://github.com/leegao/bionic-vulkan-wrapper/releases/tag/v0.0.5r3 should have fixed that specific validation error (see also #133 and #134)

**Comment by Mart-01-oss** [comment]
> [@Mart-01-oss](https://github.com/Mart-01-oss) - https://github.com/leegao/bionic-vulkan-wrapper/releases/tag/v0.0.5r3 should have fixed that specific validation error (see also [#133](https://github.com/leegao/bionic-vulkan-wrapper/issues/133) and [#134](https://github.com/leegao/bionic-vulkan-wrapper/pull/134))

looking good The vvl works fine now

[Wrapper.zip](https://github.com/user-attachments/files/21774102/Wrapper.zip)

**Comment by Ryoutarj** [comment]
Hi @leegao , thanks for the great work!  
I had the same issue with scanline artifacts or striped graphical glitches in Ultra Street Fighter IV.

Device: Poco X6 Pro
GPU: Mali G615 MC6
RAM: 12gb

![Image](https://github.com/user-attachments/assets/5440c21f-31ea-4f41-82f4-131683f1666a)

![Image](https://github.com/user-attachments/assets/f6f540ce-6b2b-4377-bd3f-ec3cd1765ed1)

[SSFIV_d3d9.log](https://github.com/user-attachments/files/21794303/SSFIV_d3d9.log)

[vvl_2025_08_14_19_23_05.SSFIV.exe.30828.txt](https://github.com/user-attachments/files/21794305/vvl_2025_08_14_19_23_05.SSFIV.exe.30828.txt)

[ssfiv_2025-08-14_19-23-00.txt.zip](https://github.com/user-attachments/files/21794329/ssfiv_2025-08-14_19-23-00.txt.zip)

[wrapper_log_2025_08_14_19_23_05.SSFIV.exe.30828.txt.zip](https://github.com/user-attachments/files/21794347/wrapper_log_2025_08_14_19_23_05.SSFIV.exe.30828.txt.zip)

[wrapper_cmds_2025_08_14_19_23_05.SSFIV.exe.30828.zip](https://github.com/user-attachments/files/21794462/wrapper_cmds_2025_08_14_19_23_05.SSFIV.exe.30828.zip)

**Comment by leegao** [comment]
@Mart-01-oss and @Ryoutarj I wonder if it might have been this: https://github.com/leegao/bionic-vulkan-wrapper/commit/dfff07cf2e60eb28c364f7a55c48d135c0ec6f6e

This happens specifically for:

1. small textures
2. images that are "far" away (or the game engine decided to use a high mip level for whatever reason)
3. images that have dimensions that aren't a perfect multiple of 4

Basically there were two bugs with the stride calculation:

1. In USE_CPU_BCN, I had mis-used the src-stride (how many texels per row in the src buffer) as the dst-stride (how many texels per row in the dst image, which should always be packed), this discrepancy is only problematic for certain mip levels and images without dimensions that are a multiple of 4
2. In CmdCopyBufferToImage, I had forgotten to unset the buffer stride since the stagingBuffer is now tightly packed

This may or may not be the cause, as it would in theory cause potential striping (that said, I don't think it would've affected the default USE_IMAGE_VIEW=1 case I see in the first set of logs)

Try this build:
[libvulkan_wrapper.so.zip](https://github.com/user-attachments/files/21795736/libvulkan_wrapper.so.zip)

You can also play around with both `USE_CPU_BCN=none/all` as well as `USE_IMAGE_VIEW=0` (which may fix some pipeline barrier issues causing the texture to be incomplete flushed at the point of rendering)

**Comment by leegao** [comment]
> [ssfiv_2025-08-14_19-23-00.txt.zip](https://github.com/user-attachments/files/21794329/ssfiv_2025-08-14_19-23-00.txt.zip)

Suspicious error:

```
Validation Error: [ VUID-vkCmdCopyBufferToImage-pRegions-00171 ] | MessageID = 0x6f4d3c00
(Warning - This VUID has now been reported 10 times, which is the duplicated_message_limit value, this will be the last time reporting it).
vkCmdCopyBufferToImage(): pRegions[0] is trying to copy 24 bytes to/from the (VkBuffer 0x3fd23000003fd23) which exceeds the VkBuffer total size of 16 bytes.
Last texel coordinate of the image is at {x = 1, y = 1, z = 0, layer = 0}
rowExtent = 16, sliceExtent = 64, layerExtent = 64
The final byte found is at bufferOffset (0) + texelOffset (20) + blockSize (4) (VK_FORMAT_R8G8B8A8_UNORM).
The Vulkan spec states: srcBuffer must be large enough to contain all buffer locations that are accessed according to Buffer and Image Addressing, for each element of pRegions (https://docs.vulkan.org/spec/latest/chapters/copies.html#VUID-vkCmdCopyBufferToImage-pRegions-00171)
Objects: 3
    [0] VkCommandBuffer 0xb400006fadfdbf50
    [1] VkBuffer 0x3fd23000003fd23
    [2] VkImage 0x39ced0000039ced
```

**Comment by leegao** [comment]
This vvl should be fixed as of #138 

> > [ssfiv_2025-08-14_19-23-00.txt.zip](https://github.com/user-attachments/files/21794329/ssfiv_2025-08-14_19-23-00.txt.zip)
> 
> Suspicious error:
> 
> ```
> Validation Error: [ VUID-vkCmdCopyBufferToImage-pRegions-00171 ] | MessageID = 0x6f4d3c00
> (Warning - This VUID has now been reported 10 times, which is the duplicated_message_limit value, this will be the last time reporting it).
> vkCmdCopyBufferToImage(): pRegions[0] is trying to copy 24 bytes to/from the (VkBuffer 0x3fd23000003fd23) which exceeds the VkBuffer total size of 16 bytes.
> Last texel coordinate of the image is at {x = 1, y = 1, z = 0, layer = 0}
> rowExtent = 16, sliceExtent = 64, layerExtent = 64
> The final byte found is at bufferOffset (0) + texelOffset (20) + blockSize (4) (VK_FORMAT_R8G8B8A8_UNORM).
> The Vulkan spec states: srcBuffer must be large enough to contain all buffer locations that are accessed according to Buffer and Image Addressing, for each element of pRegions (https://docs.vulkan.org/spec/latest/chapters/copies.html#VUID-vkCmdCopyBufferToImage-pRegions-00171)
> Objects: 3
>     [0] VkCommandBuffer 0xb400006fadfdbf50
>     [1] VkBuffer 0x3fd23000003fd23
>     [2] VkImage 0x39ced0000039ced
> ```

**Comment by Mart-01-oss** [comment]
sadly the bug still exist ,maybe it fix to @Ryoutarj

**Comment by Artewar67** [comment]
I from #118. This also not fixing bug for me.

Here additional logs and bcn dump if this help

[ReverseCollapse_d3d11.log](https://github.com/user-attachments/files/21798643/ReverseCollapse_d3d11.log)

[vvl_2025_08_15_20_10_26.ReverseCollapse.exe.5635.txt](https://github.com/user-attachments/files/21798680/vvl_2025_08_15_20_10_26.ReverseCollapse.exe.5635.txt)

[part1-artifacts_2025_08_15_20_10_29.ReverseCollapse.exe.5635.zip](https://github.com/user-attachments/files/21798810/part1-artifacts_2025_08_15_20_10_29.ReverseCollapse.exe.5635.zip)

[part2-artifacts_2025_08_15_20_10_29.ReverseCollapse.exe.5635.zip](https://github.com/user-attachments/files/21798893/part2-artifacts_2025_08_15_20_10_29.ReverseCollapse.exe.5635.zip)

[part3-artifacts_2025_08_15_20_10_29.ReverseCollapse.exe.5635.zip](https://github.com/user-attachments/files/21798894/part3-artifacts_2025_08_15_20_10_29.ReverseCollapse.exe.5635.zip)

[wrapper_cmds_2025_08_15_20_10_26.ReverseCollapse.exe.5635.txt.zip](https://github.com/user-attachments/files/21798649/wrapper_cmds_2025_08_15_20_10_26.ReverseCollapse.exe.5635.txt.zip)

[wrapper_log_2025_08_15_20_10_26.ReverseCollapse.exe.5635.txt.zip](https://github.com/user-attachments/files/21798654/wrapper_log_2025_08_15_20_10_26.ReverseCollapse.exe.5635.txt.zip)

BCN artifacts i just separated in three parts (Not archives, just files in separated folders)

**Comment by leegao** [comment]
@Mart-01-oss - could you also collect artifacts with this build - https://github.com/user-attachments/files/21812872/libvulkan_wrapper.so.zip

Instructions:

This will correctly record the src buffer as well and I can check to see if that texture above is supposed to look like that (or if the src stride is off while decoding)

The new command is:

```
DUMP_BCN=all
```

or any of `133-146` or `bc1-bc7`

**Comment by Mart-01-oss** [comment]
> [@Mart-01-oss](https://github.com/Mart-01-oss) - could you also collect artifacts with this build - https://github.com/user-attachments/files/21812872/libvulkan_wrapper.so.zip
> 
> Instructions:
> 
> This will correctly record the src buffer as well and I can check to see if that texture above is supposed to look like that (or if the src stride is off while decoding)
> 
> The new command is:
> 
> ```
> DUMP_BCN=all
> ```
> 
> or any of `133-146` or `bc1-bc7`

[Wrapper.zip](https://github.com/user-attachments/files/21813188/Wrapper.zip)

**Comment by leegao** [comment]
Oh yeah I can clearly see the scanlines in the artifacts:

for e.g. 

<img width="256" height="256" alt="Image" src="https://github.com/user-attachments/assets/413a3166-09b6-4edf-bdad-fc2b2d0b86f8" />

the weird thing is that the reference image is also striped

<img width="256" height="256" alt="Image" src="https://github.com/user-attachments/assets/e12d79ee-6f59-4d58-ae87-b97ace793d7e" />

[artifacts_2025_08_16_21_31_27.Dead Space.exe.10545.zip](https://github.com/user-attachments/files/21813480/artifacts_2025_08_16_21_31_27.Dead.Space.exe.10545.zip)

**Comment by leegao** [comment]
img 01888:

<img width="1024" height="64" alt="Image" src="https://github.com/user-attachments/assets/91f61646-2bc0-4e39-b4d0-91aec599d025" />

ref from srcBuffer:

<img width="1024" height="64" alt="Image" src="https://github.com/user-attachments/assets/d2128e8a-6b8c-4a09-a9ca-ad7f3d9d30ea" />

```
src: 0x12570000001257
.bufferOffset: VkDeviceSize = 0x0
.bufferRowLength: uint32_t = 0x0
.bufferImageHeight: uint32_t = 0x0
.imageSubresource: VkImageSubresourceLayers
  .aspectMask: VkImageAspectFlags = 0x1
  .mipLevel: uint32_t = 0x0
  .baseArrayLayer: uint32_t = 0x0
  .layerCount: uint32_t = 0x1
.imageOffset: VkOffset3D
  .x: int32_t = 0x0
  .y: int32_t = 0x0
  .z: int32_t = 0x0
.imageExtent: VkExtent3D
  .width: uint32_t = 0x400
  .height: uint32_t = 0x40
  .depth: uint32_t = 0x1
```

**Comment by leegao** [comment]
What's weird is that it's in the compressed srcBuffer too, e.g. all of the odd columns are legitimately 0s

**Comment by leegao** [comment]
One more bit - I can reproduce this locally on my Adreno 650, so it's not a Mali only issue (Turnip seems to render fine)

**Comment by leegao** [comment]
I'm going to go through Turnip and selective disable different emulation layers of the wrapper to see if I can reproduce the striping and identify the trigger

**Comment by leegao** [comment]
> Oh yeah I can clearly see the scanlines in the artifacts:
> 
> for e.g.
> 
> <img width="256" height="256" alt="Image" src="https://github.com/user-attachments/assets/413a3166-09b6-4edf-bdad-fc2b2d0b86f8" />

![Image](https://github.com/user-attachments/assets/bfc6eda8-f262-47fb-81bf-a777932535d8)
![Image](https://github.com/user-attachments/assets/62b3e0c5-7e4d-4f18-b598-526b5a673212)

Okay there's definitely something weird with how the striding is calculated, because in Turnip's native bcn mode, this would be sampled like a circle, but with even bcdec offline, this would be sampled as this elongated oval, and the actual buffer itself actually does have an entire row of zeroes too

**Comment by leegao** [comment]
I dumped the src buffer for turnip in both the glitchy and non-glitchy case, and both have the same sha1sum

**Comment by leegao** [comment]
The interesting thing is that the bufferOffset is always 0 for some reason (even when it shouldn't be), though this seems to render fine for turnip

**Comment by leegao** [comment]
Ahh, because that particular buffer is just a constant 0 buffer, so this is more or less valid (basically like a /dev/null)

I'll look at the others

**Comment by leegao** [comment]
Actually no, the src data files _ARE_ different for some reason:

<img width="32" height="32" alt="Image" src="https://github.com/user-attachments/assets/74bfcd02-d2ef-461f-ba49-9fe361790ced" /> vs  <img width="32" height="32" alt="Image" src="https://github.com/user-attachments/assets/7b879bc2-a78b-4fe6-a589-8f6295acbf63" />

turnip_s_artifacts/00721 vs turnip_t_artifacts/00721

**Comment by leegao** [comment]
decode_id = 1690

in t:

```
src: 0xb4000076d6a0e700
src_id: 719
.bufferOffset: VkDeviceSize = 0x0
.bufferRowLength: uint32_t = 0x80
.bufferImageHeight: uint32_t = 0x80
.imageSubresource: VkImageSubresourceLayers
  .aspectMask: VkImageAspectFlags = 0x1
  .mipLevel: uint32_t = 0x2
  .baseArrayLayer: uint32_t = 0x0
  .layerCount: uint32_t = 0x1
.imageOffset: VkOffset3D
  .x: int32_t = 0x0
  .y: int32_t = 0x0
  .z: int32_t = 0x0
.imageExtent: VkExtent3D
  .width: uint32_t = 0x80
  .height: uint32_t = 0x80
  .depth: uint32_t = 0x1
```

in s:

```
src: 0xb400007bd3716720
src_id: 719
.bufferOffset: VkDeviceSize = 0x0
.bufferRowLength: uint32_t = 0x80
.bufferImageHeight: uint32_t = 0x80
.imageSubresource: VkImageSubresourceLayers
  .aspectMask: VkImageAspectFlags = 0x1
  .mipLevel: uint32_t = 0x2
  .baseArrayLayer: uint32_t = 0x0
  .layerCount: uint32_t = 0x1
.imageOffset: VkOffset3D
  .x: int32_t = 0x0
  .y: int32_t = 0x0
  .z: int32_t = 0x0
.imageExtent: VkExtent3D
  .width: uint32_t = 0x80
  .height: uint32_t = 0x80
  .depth: uint32_t = 0x1
```

I'll do a cmd log to track where the buffer in 1690 came from

**Comment by leegao** [comment]
BC1 - 8x the size allocated to the src buffer

No BCn emulation - srcBuffer

```
dispatch->CreateBuffer (id=13478)
  in: device: VkDevice (handle) = 0xb400007760260f00 (id=13478)
  in: pCreateInfo: VkBufferCreateInfo* (id=13478)
    .flags: VkBufferCreateFlags = 0x0
    .size: VkDeviceSize = 0x2000
    .usage: VkBufferUsageFlags = 0x23
    .sharingMode: VkSharingMode = 0x0
    .queueFamilyIndexCount: uint32_t = 0x0
  in: pAllocator: VkAllocationCallbacks* (id=13478)
  out: result: VkResult = 0 (id=13478)
  out: *pBuffer: VkBuffer = b4000076403391e0 (id=13478)
```

With BCn emulation - srcBuffer

```
dispatch->CreateBuffer (id=19183)
  in: device: VkDevice (handle) = 0xb4000070547623e0 (id=19183)
  in: pCreateInfo: VkBufferCreateInfo* (id=19183)
    .flags: VkBufferCreateFlags = 0x0
    .size: VkDeviceSize = 0x10000
    .usage: VkBufferUsageFlags = 0x23
    .sharingMode: VkSharingMode = 0x0
    .queueFamilyIndexCount: uint32_t = 0x0
  in: pAllocator: VkAllocationCallbacks* (id=19183)
  out: result: VkResult = 0 (id=19183)
  out: *pBuffer: VkBuffer = b400006f34831650 (id=19183)
```

it looks like the game ties the src buffer size to the size of the final img instead of the original size of the data itself

**Comment by leegao** [comment]
The game uses the .str format to store data - https://www.watto.org/specs.html?specs=Archive_STR_3SLO, however this specific texture seems to be part of `frontend/frontend.str`

The file is different through, e.g. 

no emu:

```
00000000: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000010: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000020: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000030: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000040: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000050: 0000 ffff ffff ffff 2000 6231 ffff ffbf  ........ .b1....
00000060: 8110 8eee ffff 3fa8 8218 4ee6 ffff a0aa  ......?...N.....
00000070: 4008 e872 ff33 5555 0000 8a83 ffa2 55aa  @..r.3UU......U.
00000080: 0000 8a8b ff8a 55aa 4008 e872 ffcc 5555  ......U.@..r..UU
00000090: 2008 92ee ffff 22aa 4108 a9bc ffff fc2a   .....".A......*
000000a0: 0000 2229 ffff fffe 0000 ffff ffff ffff  ..")............
000000b0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000c0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000d0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000e0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000f0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000100: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000110: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000120: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000130: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000140: 0000 ffff ffff ffff 4008 e872 ffff bf58  ........@..r...X
00000150: 4008 4983 ff63 56a9 297b 0129 2d80 eeee  @.I..cV.){.)-...
00000160: 698b 0552 e055 55fd a76a 0452 77df bd68  i..R.UU..j.Rw..h
00000170: a76a 4231 aaaa 005f a76a 4129 aaaa 0055  .jB1..._.jA)...U
00000180: a76a 2129 aaaa 0055 a762 4231 aaaa 80f5  .j!)...U.bB1....
00000190: 8662 044a fdff 7809 6983 0552 0b55 557f  .b.J..x.i..R.UU.
000001a0: 6a8b 2229 780b ffef 4008 287b ffc9 956a  j.")x...@.({...j
000001b0: 4008 c76a ffff fe25 0000 ffff ffff ffff  @..j...%........
000001c0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000001d0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000001e0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000001f0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000200: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000210: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000220: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000230: 0000 ffff ffff ffff 4108 097b ffff 3f63  ........A..{..?c
```

with emu:

```
00000000: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000010: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000020: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000030: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000040: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000050: 0000 ffff ffff ffff 2000 6231 ffff ffbf  ........ .b1....
00000060: 8110 8eee ffff 3fa8 8218 4ee6 ffff a0aa  ......?...N.....
00000070: 4008 e872 ff33 5555 0000 8a83 ffa2 55aa  @..r.3UU......U.
00000080: 0000 8a8b ff8a 55aa 4008 e872 ffcc 5555  ......U.@..r..UU
00000090: 2008 92ee ffff 22aa 4108 a9bc ffff fc2a   .....".A......*
000000a0: 0000 2229 ffff fffe 0000 ffff ffff ffff  ..")............
000000b0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000c0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000d0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000e0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000000f0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000100: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000110: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000130: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000140: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000150: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000160: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000170: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000180: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000190: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000001f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000200: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000210: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000220: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000230: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000240: 0000 ffff ffff ffff 4008 e872 ffff bf58  ........@..r...X
00000250: 4008 4983 ff63 56a9 297b 0129 2d80 eeee  @.I..cV.){.)-...
00000260: 698b 0552 e055 55fd a76a 0452 77df bd68  i..R.UU..j.Rw..h
00000270: a76a 4231 aaaa 005f a76a 4129 aaaa 0055  .jB1..._.jA)...U
00000280: a76a 2129 aaaa 0055 a762 4231 aaaa 80f5  .j!)...U.bB1....
00000290: 8662 044a fdff 7809 6983 0552 0b55 557f  .b.J..x.i..R.UU.
000002a0: 6a8b 2229 780b ffef 4008 287b ffc9 956a  j.")x...@.({...j
000002b0: 4008 c76a ffff fe25 0000 ffff ffff ffff  @..j...%........
000002c0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000002d0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000002e0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
000002f0: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000300: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000310: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000320: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000330: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000340: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000350: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000360: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000370: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000380: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000390: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000400: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000410: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000420: 0000 ffff ffff ffff 0000 ffff ffff ffff  ................
00000430: 0000 ffff ffff ffff 4108 097b ffff 3f63  ........A..{..?c
00000440: 2008 087b 8f6b 9669 4983 0452 6256 55d5   ..{.k.iI..RbVU.
00000450: 8662 e120 aa2a 0278 a76a e120 0ae0 5755  .b. .*.x.j. ..WU
00000460: 6662 0000 a0fe ff77 2129 0000 a0aa fe55  fb.....w!).....U
00000470: e120 2008 00aa 5555 e120 0000 00aa 5555  .  ...UU. ....UU
```

**Comment by leegao** [comment]
part of shared\vfx\textures\eabloodLogo.tg4d

```
001cbbc0: c8dd c501 7f36 30e0 2000 6231 c06c 1701 e68e eeff ff3f a882 184e e6ff ffa0 aa40  .....60. .b1.l.......?...N.....@
001cbbe0: 08e8 72ff 3355 5500 008a 83ff a260 78e0 008a 8bff 0e17 8a55 e0cc 5555 2002 2f08  ..r.3UU......`x........U..UU ./.
001cbc00: 92e2 22aa 4108 a9bc ffff fc2a 0000 c27f 7f9f 2229 08bf eaff bf58 4008 4983 ff63  ..".A......*......").....X@.I..c
001cbc20: 56a9 297b 0129 2d80 eeee 698b 0552 e055 55fd a76a 0452 77df bd68 a76a 4231 aaaa  V.){.)-...i..R.UU..j.Rw..h.jB1..
001cbc40: 005f a703 076a 4129 e055 a76a 210c 0705 1762 e880 f586 6204 4afd ff78 0969 8305  ._...jA).U.j!....b....b.J..x.i..
001cbc60: 520b 5555 7f6a 8b22 2978 0bff ef40 0828 7bff c995 6a40 0822 0ec7 6ac0 69f7 7486  R.UU.j.")x...@.({...j@."..j.i.t.
001cbc80: 0797 22d7 097b e563 2008 087b 8f6b 9669 4983 0452 6256 55d5 8662 e120 aa2a 02c0  .."..{.c ..{.k.iI..RbVU..b. .*..
001cbca0: 75bf 00c1 77af 000a e100 00a0 feff 7721 2900 07c2 77af 01aa fe02 07aa 551a 0700  u...w.........w!)...w.......U...
001cbcc0: 0080 fcb7 ba55 dde1 0002 5555 4131 2008 0337 2aaa dde0 2000 0aff 094f ff03 0fa0  .....U....UUA1 ..7*... ....O....
001cbce0: 0bd5 e5c1 18a2 a880 2d49 83e4 5189 d555 5720 00e8 7afe c596 5a40 0821 0fa6 bd64  ........-I..Q..UW ..z...Z@.!...d
001cbd00: e7fc a502 d7e3 08e7 7aff bf63 94e7 7ae1 2089 e0ae ba45 04ef e322 8258 455a 6008  ........z..c..z. ....E...".XEZ`.
001cbd20: 80f8 df77 0121 2000 2881 8e37 ea5e e078 553d b580 0e47 e575 ffe8 fa81 2000 08ed  ...w.! .(..7.^.xU=...G.u.... ...
001cbd40: bfc8 72c3 3000 005f ffaf 0282 2800 00c3 7227 0077 7ff8 e0df 5faf ab02 2741 1807  ..r.0.._....(...r'.w...._...'A..
001cbd60: 0fd7 9fae e0fd ff00 8080 2f5f e255 ffca fba1 1020 080d d57f 5580 29ef 2b4f 2aab  ........../_.U..... ....U.).+O*.
001cbd80: f5e5 822f fffd 255a 0221 a288 8225 c772 6008 420a aaaa 2008 2883 c35f ef34 fffe  .../..%Z.!...%.r`.B... .(.._.4..
001cbda0: c99e 0007 e4e8 7abf 6f9b a6a7 7262 39f0 feff 7fe4 51c1 1800 e023 d75c 5522 e2a8  ......z.o...rb9.....Q....#.\U"..
001cbdc0: ea7a d7e2 3020 085e 55d5 8b02 bf64 41e2 afbb 0a4a 73a2 2855 55ff 0268 0107 62ef  .z..0 .^U....dA....Js.(UU..h..b.
001cbde0: fffb c8e6 51c3 30d5 b7b3 d0c6 6141 18f8 7e57 5f03 4900 08fe ffa5 8fc3 3841 10d5  ....Q.0.....aA..~W_.I.......8A..
001cbe00: 090b aac3 3820 10fb dedc 1e06 5a62 20d5 d5fd 2fc6 51a2 2057 fe57 f0e2 3061 18ef  ....8 ......Zb .../.Q. W.W..0a..
001cbe20: 80fe 77a6 d77b e05f 785c ef24 17e1 2557 775f 4229 2000 c373 3f01 2eef f5e1 0b35  ..w..{._x\.$..%Ww_B) ..s?......5
001cbe40: d5a7 6a62 390f 239f bfff fde0 72fc f9e6 c100 f745 9a02 f7c7 6a62 cfa4 07e0 fcff  ..jb9.#.....r......E....jb......
001cbe60: ef7f c3dd ef01 c349 a100 87ec c078 bef5 a439 2010 d5fd bf35 c96a c228 d535 83da  .......I.....x...9 ....5.j.(.5..
001cbe80: 8a7b 4439 ada9 0a6e 2973 2239 2e3f fad5 e86a e230 6257 f77f 4449 6220 727e bcaf  .{D9...n)s"9.?...j.0bW..DIb r~..
001cbea0: 801a 7fe0 5577 4ae3 00ff e010 adab 0080 6477 8ae0 5fbf 2b2a 0007 e620 5ff8 d8ea  ....UwJ.........dw.._.+*... _...
001cbec0: 4341 8220 3779 0bf7 2339 8120 b8e7 2895 e330 4110 7afe f802 677c 65e2 f515 f535  CA. 7y..#9. ..(..0A.z...g|e....5
001cbee0: 8541 4108 555a e28e 8035 87e0 57f7 fffc 0107 a2e3 0b2d 9757 a241 2100 0b2f bffd  .AA.UZ...5..W........-.W.A!../..
001cbf00: e77a 2129 2207 3fff e000 a76a feb6 c5bf f9e6 16e4 665a 3f4f 6f9b 4562 2131 b8ec  .z!)".?....j........fZ?Oo.Eb!1..

vs the s3tc:

00000000: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000020: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000040: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 2000 6231 ffff ffbf  ........................ .b1....
00000060: 8110 8eee ffff 3fa8 8218 4ee6 ffff a0aa 4008 e872 ff33 5555 0000 8a83 ffa2 55aa  ......?...N.....@..r.3UU......U.
00000080: 0000 8a8b ff8a 55aa 4008 e872 ffcc 5555 2008 92ee ffff 22aa 4108 a9bc ffff fc2a  ......U.@..r..UU .....".A......*
000000a0: 0000 2229 ffff fffe 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ..")............................
000000c0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
000000e0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000100: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000120: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000140: 0000 ffff ffff ffff 4008 e872 ffff bf58 4008 4983 ff63 56a9 297b 0129 2d80 eeee  ........@..r...X@.I..cV.){.)-...
00000160: 698b 0552 e055 55fd a76a 0452 77df bd68 a76a 4231 aaaa 005f a76a 4129 aaaa 0055  i..R.UU..j.Rw..h.jB1..._.jA)...U
00000180: a76a 2129 aaaa 0055 a762 4231 aaaa 80f5 8662 044a fdff 7809 6983 0552 0b55 557f  .j!)...U.bB1.....b.J..x.i..R.UU.
000001a0: 6a8b 2229 780b ffef 4008 287b ffc9 956a 4008 c76a ffff fe25 0000 ffff ffff ffff  j.")x...@.({...j@..j...%........
000001c0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
000001e0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000200: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000220: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 4108 097b ffff 3f63  ........................A..{..?c
00000240: 2008 087b 8f6b 9669 4983 0452 6256 55d5 8662 e120 aa2a 0278 a76a e120 0ae0 5755   ..{.k.iI..RbVU..b. .*.x.j. ..WU
00000260: 6662 0000 a0fe ff77 2129 0000 a0aa fe55 e120 2008 00aa 5555 e120 0000 00aa 5555  fb.....w!).....U.  ...UU. ....UU
00000280: e120 0000 00ba 55dd c120 2000 0002 5555 4131 2008 2aaa dd55 6662 2000 0aff ffd5  . ....U..  ...UUA1 .*..Ufb .....
000002a0: 8662 e120 a00b d555 6662 c118 a2a8 802d 4983 e451 89d5 5557 2000 e87a fec5 965a  .b. ...Ufb.....-I..Q..UW ..z...Z
000002c0: 4008 a66a ffff fcf9 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  @..j............................
000002e0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000300: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000320: 0000 ffff ffff ffff 0000 ffff ffff ffff 2008 e77a ffbf 6394 e77a e120 89e0 aeba  ................ ..z..c..z. ....
00000340: 4562 e120 aa22 8258 455a 6008 80f8 df77 0121 2000 28ea 5e55 c120 2008 7855 3db5  Eb. .".XEZ`....w.! .(.^U.  .xU=.
00000360: c120 0000 75ff e8fa 8120 0008 edbf c872 c330 0000 5fff af02 8228 0000 777f f8f8  . ..u.... .....r.0.._....(..w...
00000380: 4110 0000 df5f afab 4118 0000 75d7 9fae 4110 0000 fdff 0080 8118 0000 55ff cafb  A...._..A...u...A...........U...
000003a0: a110 2008 0dd5 7f55 0221 2008 2aab f555 6662 0000 822f fffd 255a 0221 a288 8225  .. ....U.! .*..Ufb.../..%Z.!...%
000003c0: c772 6008 420a aaaa 2008 2883 fffe c926 0000 ffff ffff ffff 0000 ffff ffff ffff  .r`.B... .(....&................
000003e0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000400: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000420: 0000 ffff ffff ffff 0000 e87a bf6f 9ba6 a772 6239 f0fe ff7f e451 c118 00e0 5c55  ...........z.o...rb9.....Q....\U
00000440: 2229 0000 a8ea 7ad7 e230 2008 5e55 d58b 6441 0000 fdaf bb0a 4a73 a228 5555 ff02  ")....z..0 .^U..dA......Js.(UU..
00000460: 6862 a228 55ff fbc8 e651 c330 d5b7 b3d0 c661 4118 f87e 575f 0349 0008 feff a58f  hb.(U....Q.0.....aA..~W_.I......
00000480: c338 4110 d509 0baa c338 2010 fbde dc1e 065a 6220 d5d5 fd2f c651 a220 57fe 57f0  .8A......8 ......Zb .../.Q. W.W.
000004a0: e230 6118 efa6 d77b a220 2008 5f78 5cef 8118 0000 2557 775f 4229 2000 2eef f555  .0a....{.  ._x\.....%Ww_B) ....U
000004c0: e451 a110 000b 35d5 a76a 6239 0fbf fffd 2008 e772 fcf9 e69a 0000 ffff ffff ffff  .Q....5..jb9.... ..r............
000004e0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000500: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000520: 0000 c76a bf6f 9ba4 077b 0129 fcff ef7f c349 a110 705c 5755 a218 0000 c078 bef5  ...j.o...{.).....I..p\WU.....x..
00000540: a439 2010 d5fd bf35 c96a c228 d535 83da 8a7b 4439 ada9 0a6e 2973 2239 2e3f fad5  .9 ....5.j.(.5...{D9...n)s"9.?..
00000560: e86a e230 6257 f77f 4449 6220 727e bcaf c230 2110 5577 4ae3 0349 0010 adab 008a  .j.0bW..DIb r~...0!.UwJ..I......
00000580: 0349 4118 5fbf 2b2a 0349 4120 5ff8 d8ea 4341 8220 3779 0bf7 2339 8120 b8e7 2895  .IA._.+*.IA _...CA. 7y..#9. ..(.
000005a0: e330 4110 7afe f87c 6539 2010 f515 f535 8541 4108 555a e28e 8110 0000 57f7 fffc  .0A.z..|e9 ....5.AA.UZ......W...
000005c0: a210 0000 0b2d 9757 a241 2100 0b2f bffd e77a 2129 3fff fffd 2000 a76a fef9 e616  .....-.W.A!../...z!)?... ..j....
000005e0: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff  ................................
00000600: 0000 ffff ffff ffff 0000 ffff ffff ffff 0000 ffff ffff ffff 2000 665a 3f4f 6f9b  ........................ .fZ?Oo.
00000620: 4562 2131 b8ec ef7b c349 6108 707e df57 c220 0000 6a5e f72d 0331 2008 f5ab da3a  Eb!1...{.Ia.p~.W. ..j^.-.1 ....:

```

**Comment by leegao** [comment]
Okay, so it looks like the problem is that the Dead Space engine does its own custom "padding" (with transparent texels) in order to pad textures to a specific dimension, as part of its compression scheme where it just stores the starting position for each row. However, it prefills every buffer with 0s (black texels) and uses the buffer size to calculate the padding, failing to actually pack the middle parts leading to these stripes.

I don't really see an unintrusive way to fix this since this is a very engine specific thing (beyond maybe hooking dead-space's code).

I'll also need to see what's going on with the other two games, since I don't think it's the same thing (an engine specific issue)

**Comment by leegao** [comment]
@Mart-01-oss 

[libvulkan_wrapper.so.zip](https://github.com/user-attachments/files/21823114/libvulkan_wrapper.so.zip)

potentially try this build with the following flag:

```
CHECK_FOR_STRIPING=1
```

it does force decoding to be in cpu_bcn mode, but can "revert" the extra padding added by the Dead Space game engine.

See for e.g. 

![Image](https://github.com/user-attachments/assets/dfd64540-4a86-489c-aedb-f1faaabe8fc0)

**Comment by Mart-01-oss** [comment]
Great Work ,The bug has been fixed although there's a little bit of bugs but its working great

for now using bcn=none dxvk sarek might fix some striped glitch
[wrapper_bcn_none.zip](https://github.com/user-attachments/files/21823708/wrapper_bcn_none.zip)

![Image](https://github.com/user-attachments/assets/2c210b8e-0c93-4ef7-95e2-40f5f60469b4)
![Image](https://github.com/user-attachments/assets/b7928d14-e855-41be-a497-800e6132ef9e)

while using bcn=all and dxvk 1.10.3 can cause glitches 
[wrapper_bcn_all.zip](https://github.com/user-attachments/files/21823710/wrapper_bcn_all.zip)

![Image](https://github.com/user-attachments/assets/091786f6-2a4a-45cf-b61b-25432932541b)
![Image](https://github.com/user-attachments/assets/488fe566-197f-4b0a-ab2b-88cf67188985)
![Image](https://github.com/user-attachments/assets/eb207ba7-4e43-406b-9c92-c8999f0c97ae)

**Comment by Mart-01-oss** [comment]
I need to play the ingame(1 hours is probably enough) if i can trigger or find any bugs , then might close the issue as well

**Comment by leegao** [comment]
> while using bcn=all and dxvk 1.10.3 can cause glitches [wrapper_bcn_all.zip](https://github.com/user-attachments/files/21823710/wrapper_bcn_all.zip)
> 
> ![Image](https://github.com/user-attachments/assets/091786f6-2a4a-45cf-b61b-25432932541b) ![Image](https://github.com/user-attachments/assets/488fe566-197f-4b0a-ab2b-88cf67188985) ![Image](https://github.com/user-attachments/assets/eb207ba7-4e43-406b-9c92-c8999f0c97ae)

ahh that's interesting, it looks like in these images, we're wrongly detecting some of these textures as being striped (and discarding half of their rows)

**Comment by leegao** [comment]
Ahh it looks like it's wrongly using host compute shader for some reason (might be some weird interaction with the artifact dumping)

**Comment by leegao** [comment]
I can confirm that I can repro it too locally, only with USE_CPU_BCN=true as well:

<img width="1560" height="668" alt="Image" src="https://github.com/user-attachments/assets/36fe62f1-b130-431e-84b8-59cfd1c9d139" />

Looks like cpu_bcn uses some of the striping transforms even when is_striped is false, leading to this issue

**Comment by leegao** [comment]
@Mart-01-oss this build should fix use_cpu_bcn=all as well

[libvulkan_wrapper.so.zip](https://github.com/user-attachments/files/21825131/libvulkan_wrapper.so.zip)

**Comment by leegao** [comment]
@Mart-01-oss - this build should fix the problem with use_cpu_bcn (disregard the previous message)

[libvulkan_wrapper.so.zip](https://github.com/user-attachments/files/21825239/libvulkan_wrapper.so.zip)

**Comment by Mart-01-oss** [comment]
> [@Mart-01-oss](https://github.com/Mart-01-oss) - this build should fix the problem with use_cpu_bcn (disregard the previous message)
> 
> [libvulkan_wrapper.so.zip](https://github.com/user-attachments/files/21825239/libvulkan_wrapper.so.zip)

It fixed With BCN=ALL, there are bugs that can trigger strip glitch. eg= turning off shadow and spesific env option ,i debug it later.

![Image](https://github.com/user-attachments/assets/dc56e9ad-2133-42ab-ad78-63ca3fbfef5e)

(hair also bug , strip glitch)
https://github.com/user-attachments/assets/06158072-e77f-4015-9d40-ab0b645e90a0

**Comment by Mart-01-oss** [comment]
@leegao can you take look at this idk what causing this
(npc hair shooting those weird glitch,Looks like a common issues)
(already tried limiting framerate and vsync off doesn't fix it)
https://steamcommunity.com/app/17470/discussions/0/1643169167165884622/
https://www.reddit.com/r/DeadSpace/comments/119g438/anyone_know_how_to_fix_this_on_pc/

[Screenrecorder-2025-08-18-14-46-53-372.zip](https://github.com/user-attachments/files/21829048/Screenrecorder-2025-08-18-14-46-53-372.zip)

(wrapper_log)
[Winlator.zip.001.zip](https://github.com/user-attachments/files/21830059/Winlator.zip.001.zip)
[Winlator.zip.002.zip](https://github.com/user-attachments/files/21830065/Winlator.zip.002.zip)
[Winlator.zip.003.zip](https://github.com/user-attachments/files/21830069/Winlator.zip.003.zip)
[Winlator.zip.004.zip](https://github.com/user-attachments/files/21830077/Winlator.zip.004.zip)
[Winlator.zip.005.zip](https://github.com/user-attachments/files/21830080/Winlator.zip.005.zip)

(artifacts)
[Wrapper.zip.001.zip](https://github.com/user-attachments/files/21830235/Wrapper.zip.001.zip)
[Wrapper.zip.002.zip](https://github.com/user-attachments/files/21830237/Wrapper.zip.002.zip)
[Wrapper.zip.003.zip](https://github.com/user-attachments/files/21830239/Wrapper.zip.003.zip)

Using dxvk 1.7 fixed(also 1.10.3arm64ec rarely happens just split of second but the performance is good ) it but the performance was very low compared to sarek

**Comment by Mart-01-oss** [comment]
finally figured out what's going ,the vsync in game causing weird glitch to fix it (disable the vsync in game and enable vsync in wine or dxvk.conf this only work in Nvidia) hard to say it's fixed but its playable
looks like not related to driver anymore.
